### PR TITLE
Changing how /status method returns its values to try and merge with …

### PR DESCRIPTION
**Pull request by louis-byers**
…any pre-existing tags from previous executors if any.

A shot at addressing the issue mentioned in https://github.com/jina-ai/executor-hnsw-postgres/issues/23

### CODE REVIEW

**Review by JoanFM — CHANGES_REQUESTED** [review]
I would recommend not returning a `DocumentArray` with updated `tags`, but to return status as a dict, https://docs.jina.ai/fundamentals/executor/executor-api/#method-return

Like this u will get a subdict with `__results__` for each executor

**Comment by louis-byers** [comment]
I think switching to `__results__` for this type of endpoint is a good suggestion for this kind of endpoint. Bonus you get the replica index for free in the key. This actually solves my problem if I use this strategy for my executors, because it makes it so that the current implementation of this hub executor doesn't clobber my status values which I was dropping in as tags. The `__results__` is a much better spot for this metadata.

As this change for this hub executor changes the API it would require more extensive changes than what I proposed e.g. docs and tests, so I'll close this, but won't be able to contribute that change for at least a week. I am busy with my other work obligations and in order to get the test suite running seems like I gotta get a virtual env for this repo actually running.

**Comment by JoanFM** [comment]
> I think switching to `__results__` for this type of endpoint is a good suggestion for this kind of endpoint. Bonus you get the replica index for free in the key. This actually solves my problem if I use this strategy for my executors, because it makes it so that the current implementation of this hub executor doesn't clobber my status values which I was dropping in as tags. The `__results__` is a much better spot for this metadata.
> 
> As this change for this hub executor changes the API it would require more extensive changes than what I proposed e.g. docs and tests, so I'll close this, but won't be able to contribute that change for at least a week. I am busy with my other work obligations and in order to get the test suite running seems like I gotta get a virtual env for this repo actually running.

So @louisconcentricsky could u adapt the `PR` to apply this change?

**Comment by louis-byers** [comment]
@JoanFM absolutely, I am just trying to slide it into my work schedule.

**Comment by louis-byers** [comment]
@JoanFM made the changes

**Review by JoanFM — APPROVED** [review]

**Comment by JoanFM** [comment]
Hey @louisconcentricsky ,

Sorry for the delay, thanks for the contribution!

**Comment by louis-byers** [comment]
Glad to help out even a little bit. @JoanFM  It'll be the last contribution from this account, my company Concentric Sky got acquired and so this account will be going away. After the dust settles in my life I hope to get back to see what cool stuff JINA is up to and maybe contribute again.

**Pull request merged**
